### ISSUE TITLE
Building on Windows, errors and fixes.

### ISSUE THREAD

**Issue by antithing** [bytedance/particle-sfm#20]
Hi, and thank you for this code! I am seeing errors when running the example, can you help me to debug them please?

```
python run_particlesfm.py --image_dir ./example/snowboard/images --output_dir ./outputs/snowboard/
[ParticleSFM] Running pairwise optical flow inference......
Loading weights:  D:\Testing\OFFLINE\PSFM\particle-sfm\third_party\RAFT\models/raft-things.pth
  0%|                                                                                           | 0/65 [00:00<?, ?it/s]C:\Users\B\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\TensorShape.cpp:3484.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
  0%|                                                                                           | 0/65 [00:02<?, ?it/s]
Traceback (most recent call last):
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 158, in <module>
    particlesfm(args, args.image_dir, args.output_dir, skip_exists=args.skip_exists, keep_intermediate=args.keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 105, in particlesfm
    traj_dir = connect_point_trajectory(args, image_dir, output_dir, skip_exists=skip_exists, keep_intermediate=keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 33, in connect_point_trajectory
    compute_raft_custom_folder(image_dir, flow_dir, skip_exists=skip_exists)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\third_party\RAFT\compute_raft_custom_folder.py", line 85, in compute_raft_custom_folder
    infer_optical_flows(model, image_dir, output_dir, skip_exists=skip_exists)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\third_party\RAFT\compute_raft_custom_folder.py", line 57, in infer_optical_flows
    flow_write(flow_save_name, flow_forward)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\third_party\RAFT\custom_utils.py", line 42, in flow_write
    f = open(filename,'wb')
FileNotFoundError: [Errno 2] No such file or directory: './outputs/snowboard/optical_flows\\flow_f\\images\\00000.flo'
```

I have downloaded all models and placed them in the folders, what might be happening here?

**Comment by antithing** [comment]
Ah, I have solved these by adding:


```
            if not os.path.exists(flow_save_path + '/images'):
                os.makedirs(flow_save_path + '/images')
            if not os.path.exists(flow_bk_save_path + '/images'):
                os.makedirs(flow_bk_save_path + '/images')

```

It seems the directories were not made.

I know have the flow files saved. Next issue:


```
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 158, in <module>
    particlesfm(args, args.image_dir, args.output_dir, skip_exists=args.skip_exists, keep_intermediate=args.keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 105, in particlesfm
    traj_dir = connect_point_trajectory(args, image_dir, output_dir, skip_exists=skip_exists, keep_intermediate=keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 39, in connect_point_trajectory
    from point_trajectory import main_connect_point_trajectories
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\__init__.py", line 1, in <module>
    from .main_connect_point_trajectories import main_connect_point_trajectories
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\main_connect_point_trajectories.py", line 23, in <module>
    from .track import track
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\track.py", line 21, in <module>
    from .trajectory import Trajectory, IncrementalTrajectorySet
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\trajectory.py", line 23, in <module>
    from .optimize.build import particlesfm
ImportError: DLL load failed while importing particlesfm: The specified module could not be found.
```

In the `.optimize.build` folder, I have the 'particlesfm.cp39-win_amd64.pyd' file created when the project was built. Is this what needs to be loaded? Why would this be failing?

**Comment by antithing** [comment]
Aha, this one is solved by adding all the third party dll files (ceres etc) to the directory as well as the pyd. 

Next one!

```
[ParticleSfM] Connecting (optimization enabled) point trajectories from optical flows.......
Traceback (most recent call last):
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 158, in <module>
    particlesfm(args, args.image_dir, args.output_dir, skip_exists=args.skip_exists, keep_intermediate=args.keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 105, in particlesfm
    traj_dir = connect_point_trajectory(args, image_dir, output_dir, skip_exists=skip_exists, keep_intermediate=keep_intermediate)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\run_particlesfm.py", line 41, in connect_point_trajectory
    main_connect_point_trajectories(flow_dir, traj_dir, sample_ratio=args.sample_ratio, flow_check_thres=args.flow_check_thres, skip_path_consistency=args.skip_path_consistency, skip_exists=skip_exists)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\main_connect_point_trajectories.py", line 53, in main_connect_point_trajectories
    trajs = track_optimize(flows_f, flows_f2, occ_maps, occ_maps_s2, sample_ratio)
  File "D:\Testing\OFFLINE\PSFM\particle-sfm\point_trajectory\track_optimize.py", line 29, in track_optimize
    h, w = flows[0].shape[:2]
IndexError: list index out of range
```

**Comment by antithing** [comment]
...this one was related to the first, `images` needs to be added to the folder path.

```
 flow_f_dir = os.path.join(flow_dir, "flow_f/images")
    flow_b_dir = os.path.join(flow_dir, "flow_b/images")
    flows_f, flows_b = load_flows(flow_f_dir), load_flows(flow_b_dir)
    error_maps, occ_maps = flow_check(flows_f, flows_b, thres=flow_check_thres)
    n_images = len(flows_f) + 1

    # load stride-2 optical flow
    if not skip_path_consistency:
        flow_f2_dir = os.path.join(flow_dir, "flow_f2/images")
        flow_b2_dir = os.path.join(flow_dir, "flow_b2/images")
        flows_f2, flows_b2 = load_flows(flow_f2_dir), load_flows(flow_b2_dir)
        error_maps_s2, occ_maps_s2 = flow_check(flows_f2, flows_b2, thres=flow_check_thres)
```

**Comment by antithing** [comment]
also needed to add this:

dummy_dir = sfm_dir / 'dummy_features'
    if not os.path.exists(dummy_dir):
        os.makedirs(dummy_dir)
   # dummy_dir.mkdir()

to `import_feature_matches.py`

As well as build colmap 3.8 from source and copy it to local folder where I can link the binaries in the python code. 
I build the gmapper lib and exe, and link those in python as well.

Now I have it running on Windows! Everything except the motion seg module, which I still see errors with, i iwll keep looking into it.

Happy to submit a Windows branch / PR at some point if you are interested.

Thanks!

**Comment by antithing** [comment]
After days of looking into this, it can be resolved by adding:

```
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)
torch.backends.cuda.enable_math_sdp(True)
```

in `main_motion_segmentation.py`

I know have this code successfully running on Windows!  Thanks
